- config/settings.yml
Changed frequencies of Andersen AFB to match the ones in the charts.
> changed andersen afb freqs and added callsigns

- config/settings.yml
Reverts stab-virtual-jabog32/fpt#12
> Revert "Add Weapon and A/C AH64D"

- config/settings.yml
added pilot : Snake
added Callsign/IFF:
bambam (47xx), Cobra(50xx),Cowboy(51xx), Viper (52xx),Hammer (53xx), Falcon (54xx), Fury (55xx), Nasty (56xx), Outlaw (57xx)
> siehe details (pilot, callsigns/IFF)

- config/settings.yml
Updated:
- F-5E
- F-14B
- JF-17
- M-2000C
- L-39C (former L-39)
- C-101EB (former C-101) 
- UH-1H
- KA-50
- Mi-8
- Mi-24P
Added:
- L-39ZA
- C-101CC
- AJS37
- F-14A-135-GR
- SA342L/M/Minigun/Mistral
> Added and updated airframes

- config/settings.yml
Syrien Airfields. Carrier, Navaids, Waypoints hinzugefügt
> Syria Update

- config/settings.yml
> Added addiks as pilot

- config/settings.yml
Bitte vorab einmal prüfen bzgl. "airframe" und "Tacan", geht das so?
> Adding Cyprus FARPs

- config/settings.yml
texaco2:
callsign: TEXACO 2
type: TANKER
aiframe: KC-130
comms: 244.78
tacan: 44Y
position: "TEXACO2: (N3424 E03403)"
altitude: FL150
speed: 250
shell3:
callsign: SHELL 3
type: TANKER
aiframe: KC-135
comms: 278.75
tacan: 93Y
position: "SHELL3: (N3436 E03419)"
altitude: FL170
speed: 215
> add new Tanker Shell3 + TXC2 for ETTR

- config/settings.yml
> Added ADM-141A to F/A-18C

- config/settings.yml
> AH64 Weight and Weapon Names changed to according actual stable

- config/settings.yml
- Added all Isreali airports
- added 2 navaids (BGN, NAT)
> Added inital support for Sinai map

- config/settings.yml
> Added Stoner

- app/views/mdc/show.text.erb
Reverts stab-virtual-jabog32/fpt#90
> Revert "try to fix notes having no linebreaks #2"

- app/views/mdc/show.text.erb
Reverts stab-virtual-jabog32/fpt#89
> Revert "Try to fix notes having no linebreaks"

- .gitignore
- config/settings.yml
Added to F-15E
- AGM-154A
- GBU-31(V)3/B
- GBU-31(V)1/B
- GBU-38
- GBU-54
> Added JSOW and JDAM to F-15E

- config/settings.yml
Reverts stab-virtual-jabog32/fpt#110
> Revert "Update error Kiowa"

- README.md
This is the first branch for general enhancements from here on.
It only touches the readme markdown page to explain everything relevant on GitHub.
From here on further issue based branches will be created und merged via pull request.
> Poet-enhancement1001

- config/settings.yml
September Update for new Hornet Rookies
- Cloud
- Joker
> Joker and Cloud added

- config/settings.yml
> Added STTR Briefing Link

- config/settings.yml
Updated Kola airbase freqs to align with radio card
> Updated Kola airbase freqs to align with radio card

- config/settings.yml
> STTR: Added tanker waypoints

- config/settings.yml
> Added STTR Waypoints

- config/settings.yml
- public/static-overlay.yaml
Changed STTR WP names as A-10C CDU doesnt accepted dashes
> Changed STTR WP names

- config/settings.yml
- public/static-overlay.yaml
- Added ESR03.07 GPS Targets
- Updated CWG Tacan for Bitburg
> Added ESR03.07 GPS Targets

- config/settings.yml
- public/static-overlay.yaml
Added 3 STTR Waypoints:
OBAPA
GOGPI
RIMER
> Added 3 STTR Waypoints

- config/settings.yml
- public/static-overlay.yaml
Introduce three new waypoints, GIBMO, GILGU, and LULAX, with their respective coordinates and properties.
> Add new STTR waypoints: GIBMO, GILGU, LULAX

- config/settings.yml
Eliminate Joker from the list of pilots.
> Remove pilot Joker
